config/routes.rb
Sipag::Application.routes.draw do
  
  resources :lots

  resources :regions

  resources :widgets, only: [:index]
  resources :hello, only: [:index]

  resources :coins

  get "bodega/index"

  resources :entries

  resources :beneficiaries

  resources :tipo_products

  resources :distributors

  resources :makers

  resources :products

  resources :elements

  resources :sicks

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :plagues

  root to: 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
  get '/plaguen', to: 'plagues#new'
  get '/bodega', to: 'bodega#index'
  get '/toEntry', to: 'products#toEntry'
  get '/llevar', to: 'products#llevar'
  get '/produccion', to: 'bodega#index'
  

end

app/models/tipo_product.rb
# == Schema Information
#
# Table name: tipo_products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  descripcion :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  color       :string(255)
#

class TipoProduct < ActiveRecord::Base
	has_many :products
end

app/controllers/tipo_products_controller.rb
class TipoProductsController < ApplicationController
  before_filter :signed_in_user
  # GET /tipo_products
  # GET /tipo_products.json
  def index
    @tipo_products = TipoProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipo_products }
    end
  end

  # GET /tipo_products/1
  # GET /tipo_products/1.json
  def show
    @tipo_product = TipoProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipo_product }
    end
  end

  # GET /tipo_products/new
  # GET /tipo_products/new.json
  def new
    @tipo_product = TipoProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipo_product }
    end
  end

  # GET /tipo_products/1/edit
  def edit
    @tipo_product = TipoProduct.find(params[:id])
  end

  # POST /tipo_products
  # POST /tipo_products.json
  def create
    @tipo_product = TipoProduct.new(params[:tipo_product])

    respond_to do |format|
      if @tipo_product.save
        format.html { redirect_to @tipo_product, notice: 'Tipo product was successfully created.' }
        format.json { render json: @tipo_product, status: :created, location: @tipo_product }
      else
        format.html { render action: "new" }
        format.json { render json: @tipo_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_products/1
  # PUT /tipo_products/1.json
  def update
    @tipo_product = TipoProduct.find(params[:id])

    respond_to do |format|
      if @tipo_product.update_attributes(params[:tipo_product])
        format.html { redirect_to @tipo_product, notice: 'Tipo product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipo_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_products/1
  # DELETE /tipo_products/1.json
  def destroy
    @tipo_product = TipoProduct.find(params[:id])
    @tipo_product.destroy

    respond_to do |format|
      format.html { redirect_to tipo_products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tipo_products_helper.rb
module TipoProductsHelper
end

app/views/tipo_products/_form.html.erb
<%= form_for(@tipo_product) do |f| %>
  <% if @tipo_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_product.errors.count, "error") %> prohibited this tipo_product from being saved:</h2>

      <ul>
      <% @tipo_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_products/edit.html.erb
<h1>Editing tipo_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_product %> |
<%= link_to 'Back', tipo_products_path %>

app/views/tipo_products/index.html.erb
<h1>Listing tipo_products</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipo_products.each do |tipo_product| %>
  <tr>
    <td><%= tipo_product.name %></td>
    <td><%= tipo_product.descripcion %></td>
    <td><%= tipo_product.color %></td>
    <td><%= link_to 'Show', tipo_product %></td>
    <td><%= link_to 'Edit', edit_tipo_product_path(tipo_product) %></td>
    <td><%= link_to 'Destroy', tipo_product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tipo product', new_tipo_product_path %>

app/views/tipo_products/new.html.erb
<h1>New tipo_product</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_products_path %>

app/views/tipo_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tipo_product.name %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @tipo_product.descripcion %>
</p>
<p>
  <b>Color:</b>
  <%= @tipo_product.color %>
</p>


<%= link_to 'Edit', edit_tipo_product_path(@tipo_product) %> |
<%= link_to 'Back', tipo_products_path %>