config/routes.rb
Sipag::Application.routes.draw do
  
  resources :lots

  resources :regions

  resources :widgets, only: [:index]
  resources :hello, only: [:index]

  resources :coins

  get "bodega/index"

  resources :entries

  resources :beneficiaries

  resources :tipo_products

  resources :distributors

  resources :makers

  resources :products

  resources :elements

  resources :sicks

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :plagues

  root to: 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
  get '/plaguen', to: 'plagues#new'
  get '/bodega', to: 'bodega#index'
  get '/toEntry', to: 'products#toEntry'
  get '/llevar', to: 'products#llevar'
  get '/produccion', to: 'bodega#index'
  

end

app/models/element.rb
# == Schema Information
#
# Table name: elements
#
#  id          :integer          not null, primary key
#  nombre      :string(255)
#  descripcion :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Element < ActiveRecord::Base
	attr_accessible :nombre, :descripcion
	validates :nombre, presence: true
	has_many :formulations
	has_many :products, through: :formulations

	def self.search(search)  
	    if search  
	      where('nombre LIKE ?', "%#{search}%")  
	    else  
	      scoped  
	    end  
	end  
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_filter :signed_in_user

  helper_method :sort_column, :sort_direction
  # GET /elements
  # GET /elements.json
  def index
    @ajax_search = params[:ajax_search] == "true" ? true : false
    puts "sort_direction = " + sort_direction

    @elements = Element.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
    

    respond_to do |format|
      format.html # index.html.erb     
       format.js   # index.js.erb
      format.json { render json: @elements }
    end
  end

  # GET /elements/1
  # GET /elements/1.json

  # GET /elements/new
  # GET /elements/new.json
  def new
    @element = Element.new

    respond_to do |format|
      format.html # new.html.erb
      format.js   # new.js.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = Element.find(params[:id])
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(params[:element])

    respond_to do |format|
      if @element.save
        format.html { redirect_to elements_path, notice: 'Element was successfully created.' } 
        format.js { flash[:info]="Elemento creado con exito." }               
        format.json { render json: elements_path, status: :created, location: @element }
      else
        format.html { render action: "new" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

 
  # PUT /elements/1
  # PUT /elements/1.json
  def update
    @element = Element.find(params[:id])

    respond_to do |format|
      if @element.update_attributes(params[:element])
        format.html { redirect_to elements_path, notice: 'Elemento editado correctamente.' }
        format.js { flash.now[:info]='Elemento Actualizado con exito' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element = Element.find(params[:id])
    @element.destroy
    @elements = Element.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html { redirect_to elements_url }
      format.json { head :no_content }
      format.js { flash.now[:info]='Elemento eliminado correctamente' }
    end
  end

private  
  def sort_column
    # column varmi diye kontrol ediliyor, yoksa name default   
    Element.column_names.include?(params[:sort]) ? params[:sort] : "nombre"   
  end  
 
  # sort icin default direction asc
  def sort_direction
    # karakter kontrol yapiliyor security icin  
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"    
  end  



end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_edit.html.erb
<% provide(:title, 'Enfermedades') %>
<% provide(:boton, 'Guardar Cambios') %>
<div class="page-header">
    <h1 class="pull-left">Editar Elemento</h1>
    <div class="pull-right">
        <%= link_to new_element_path, :remote => true,
        :class => "btn btn-primary", :style => "margin-right:10px; height:15px;" do%>
        <i class="icon-star icon-white"></i> Nuevo Elemento
        <% end %>
    </div>
</div>

<div class= "row-fluid">
	<div class="span12">
		<%= render 'form' %>

	</div>
</div>

app/views/elements/_element_table.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="table table-striped table-bordered table-condensed sortable">
  <thead>
  <tr>    
    <th style="width: 300px;"><%= sortable "nombre", "Nombre"%></th>
    <th>Descripcion</th>
     <th style="width: 40px;"></th>
   
  </tr>
</thead>
 <tbody>
<% @elements.each do |element| %>
  <tr>
    <td><%= link_to element.nombre, edit_element_path(element), :remote => true %></td>
    <td><%= element.descripcion.first(50) +"..." %></td>  
    <td valign="top"> 
                <%= link_to edit_element_path(element), :remote => true, :style=>'height: 14px;', :title=>'Edit' do%> 
                    <i class="icon-edit"></i> 
                <% end %> 
                
                <a style="height: 14px; padding-left: 5px;" title="Delete"
                    data-backdrop="static" data-keyboard="true"
                    href="javascript:;"
                    onclick="show_confirm_modal('<%= element_path(element) %>',
                    'Está seguro que desea Eleminar el elemento : <%= element.nombre%>');"> 
                    <i class="icon-remove"></i> 
                </a>
          </td>    
  </tr>
<% end %>
</tbody>
<tfoot>
        <tr>
            <td colspan="5"> <%= will_paginate @elements%> </td>
        </tr>
    </tfoot>
</table>

app/views/elements/_form.html.erb
<%= form_for(@element,  remote: true) do |f| %>
  <% if @element.errors.any? %>
    <div id="alert alert-block alert-error">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="control-group <%= 'error' if @element.errors[:nombre].present? %>">
        <label for="nombre" class="control-label">Nombre</label>
        <div class="controls">
            <%= f.text_field :nombre, :maxlength => "100" %>
        </div>
    </div>

     <div class="control-group <%= 'error' if @element.errors[:descripcion].present? %>">
        <label for="descripcioin" class="control-label">Descripcion</label>
        <div class="controls">
            <%= f.text_field :descripcion, :maxlength => "100" %>
        </div>
    </div>

  
 <div class="actions">
  <%= f.submit yield(:boton), :class => "btn btn-primary"%>
          
 <%= link_to :back, :remote => true, :type => "reset", :class => "btn" do%>
        <i class="icon-chevron-left"></i>Cancelar
    <% end %>  
</div>
<% end %>

app/views/elements/_index.html.erb
<%= render '/layouts/confirm_modal'%>

<%= form_tag  elements_path, :method => 'get', :id => "ajax_search_form" do %>
<div class="page-header">
    <h1 class="pull-left">Elementos</h1>
    <div class="pull-right">
        <%= link_to new_element_path, :remote => true,
        :class => "btn btn-primary", :style => "margin-right:10px; height:15px;" do%>
            <i class="icon-star icon-white"></i> Nuevo Elemento
        <% end %>

        <div id="quicksearch" class="search-box">
            <%= text_field_tag :search, params[:search], :placeholder => "Search"  %>
            
        </div>
        <%= hidden_field_tag :ajax_search, "true" %>
    </div>
</div>
<div class="row-fluid">
    <div id="table_div" class="span12">
        <%= render :partial => 'element_table' %>
    </div>
</div>
<% end %>





app/views/elements/_new.html.erb
<% provide(:title, 'Elementos') %>
<% provide(:boton, 'Salvar Elemento') %>

<div class="page-header">
  <h1 class="pull-left">Nuevo Elemento</h1>
</div>

<div class= "row-fluid">
  <div class="span12">
    <%= render 'form' %>

  </div>
</div>

app/views/elements/create.js.erb
$.getScript("/elements/");
history.pushState(null, "", "/elements/");

app/views/elements/destroy.js.erb
// $('.delete_element').bind('ajax:success', function() {  
//         $(this).closest('tr').fadeOut();
// });  
$('#body_content').html('<%= escape_javascript(render("index")) %>');
$('#messages').html('<%= escape_javascript(render("/layouts/messages")) %>');

app/views/elements/edit.js.erb
$('#body_content').html('<%= escape_javascript(render("edit")) %>');

app/views/elements/index.html.erb
<%= render 'index' %>

app/views/elements/index.js.erb
<% if @ajax_search == true %>
  $('#table_div').html('<%= escape_javascript(render("element_table")) %>');
<% else %>
  $('#body_content').html('<%= escape_javascript(render("index")) %>');  
<% end %>  
  
$('#messages').html('<%= escape_javascript(render("/layouts/messages")) %>');


app/views/elements/new.js.erb
$('#body_content').html('<%= escape_javascript(render("new")) %>');

app/views/elements/show.html.erb
<% provide(:title, @element.nombre) %>

<div class="container-fluid">
		  <div class="row-fluid">
		    
		    <div class="span8">
		     <h1>
		     	<%= @element.nombre %>
		     </h1>

		     <%= @element.descripcion %>
		   
		  </div>
				
		</div>
<div class="btn-group span8">

	           		<%= link_to 'Editar', edit_element_path(@element), class: "btn btn-primary", role: "button"  %> |
					<%= link_to 'Regresar', elements_path, class: "btn btn-primary",role: "button"  %>
                  
           		</div>  
</div>
 		

app/views/elements/update.js.erb
$.getScript("/elements/");
history.pushState(null, "", "/elements/");