config/routes.rb
Sipag::Application.routes.draw do
  
  resources :lots

  resources :regions

  resources :widgets, only: [:index]
  resources :hello, only: [:index]

  resources :coins

  get "bodega/index"

  resources :entries

  resources :beneficiaries

  resources :tipo_products

  resources :distributors

  resources :makers

  resources :products

  resources :elements

  resources :sicks

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :plagues

  root to: 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
  get '/plaguen', to: 'plagues#new'
  get '/bodega', to: 'bodega#index'
  get '/toEntry', to: 'products#toEntry'
  get '/llevar', to: 'products#llevar'
  get '/produccion', to: 'bodega#index'
  

end

app/models/lot.rb
# == Schema Information
#
# Table name: lots
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  descripcion  :text
#  area         :float
#  unidadmedida :string(255)
#  region_id    :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Lot < ActiveRecord::Base
attr_accessible :name, :descripcion, :area, :unidadmedida, :region_id
belongs_to :region

def self.search(search)  
	    if search  
	      where('name LIKE ?', "%#{search}%")  
	    else  
	      scoped  
	    end  
	end  
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
#  before_action :set_lot, only: [:show, :edit, :update, :destroy]

  # GET /lots
  def index
    @ajax_search = params[:ajax_search] == "true" ? true : false
    @lots = Lot.search(params[:search]).paginate(per_page: 10, page: params[:page])
     
    respond_to do |format|

       format.html # index.html.erb
       format.js   # index.js.erb
       format.json { render json: @lots }
    end
  end

  # GET /lots/1
  def show
     @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/new
  def new
    @lot = Lot.new

   respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @lot }
    end
  end

  # GET /lots/1/edit
  def edit

    @lot = Lot.find(params[:id])
     respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @lot }
    end
  end

  # POST /lots
  def create
    @lot = Lot.new(params[:lot])

   
    respond_to do |format|
      if @lot.save
        format.html { redirect_to lots_path, notice: 'Lote fue guardado correctamente' }
         format.js  { flash.now[:info]='Elemento creado con exito'}
        format.json { render json: @lot, status: :created, location: @lot }
      else
        format.html { render action: "new" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lots/1
  def update
   
 @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to @lot, notice: 'Lote was successfully updated.' }
        format.js  { flash.now[:info]='Elemento Actualizado con exito'}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
 end
  # DELETE /lots/1
def destroy
    @lot = Lot.find(params[:id])
    @lot.destroy
    @lots = Lot.search(params[:search]).paginate(per_page: 5, page: params[:page])
    
    respond_to do |format|
      format.html { redirect_to lots_url }
      format.json { head :no_content }
      format.js { flash.now[:info]='Elemento eliminado correctamente' }
    end
  end


private
    # Use callbacks to share common setup or constraints between actions.
    def set_lot
      @lot = Lot.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lot_params
      params.require(:lot).permit(:name, :descripcion, :area, :unidadmedida, :region_id)
    end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_edit.html.erb
<h1>Editando Lotes</h1>

<%= render 'form' %>

<%= link_to 'atras', lots_path %>

app/views/lots/_form.html.erb
<%= form_for(@lot, remote: true) do |f| %>
  <% if @lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% @lot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row-fluid">
  <div class="span6">
    <%= f.label :name %><br>
    <%= f.text_field :name,  placeholder: "Nombre de Lote", required: true %>
  </div>
  <div class="span6">
    <%= f.label :area %><br>
    <%= f.text_field :area,  placeholder: "Dimension del Lote", required: true  %>
  </div>
</div>

<div class="row-fluid">

    <div class="span6">
      <%= f.label :unidadmedida %><br/>
      <%= f.select(:unidadmedida, [['Hectareas','Hectareas'], ['Manzanas','Manzanas']]) %> 
    </div>
    <div class="span6">
      <%= f.label :region_id %><br>
      <%= f.collection_select :region_id, Region.all, :id,:name %>
    </div>

<div class="row-fluid">
  <div class="span12">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion,  placeholder: "Descripcion Reelevante del Lote", required: true  %>
  </div>
</div>  
  <br/>
  
<%= f.submit 'Guardar', class: "btn btn-primary" %>
 
<% end %>

app/views/lots/_index.html.erb
<% provide(:title, 'Lotes') %>

<h1>Lotes</h1>
<%= render '/layouts/confirm_modal'%>
  <script type="text/javascript">

$(function(){
    
    $("#quicksearch input").bind("keyup",function(){
        var form = $("#ajax_search_form");
        var url = form.attr('action') + '?' + form.serialize();
        url = url.replace("ajax_search=true", "ajax_search=");
        history.pushState({
            path:url
        }, "", url);

        $.get(form.attr("action"), form.serialize(), null, "script");        
    });


});
</script>

<div class="container-fluid">
      <div class="row-fluid">
         <div class="span6"> <!-- 1era Columna -->
           <div class="btn-group span4">
                  <%= link_to "Nuevo", new_lot_path,  :remote => true,
        :class => "btn btn-primary", :'data-target'=>"#addModal",  role: "button", :'data-toggle' => "modal"%>        

                  
           </div>  
        </div> 
        <%= form_tag(lots_path, :method => 'get', class: "form-search", :id => "ajax_search_form") do %>  
                     <div id="quicksearch" class="search-box">
                      <%= text_field_tag :search,  params[:search], placeholder: "Buscar Lote Especifico" %>  
                      </div>
                     <%= hidden_field_tag :ajax_search, "true" %>
        <% end %>  
        <div id="table_div" class="span12" >
          <%= render 'tabla_lot' %>  
          <%= will_paginate @lots %>
       </div>
         
         <!-- MODAL -->
              <div id="addModal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h3 id="myModalLabel">Crear Nuevo Lote</h3>
                </div>
                  <div class="modal-body" id="bodyNewRegion">

                  

                  
                </div>
                
            </div>
  </div>

</div>

app/views/lots/_new.html.erb
<% provide(:title, 'Lotes') %>
<% provide(:boton, 'Salvar Lotes') %>
<h1>Nuevo Lote</h1>

<%= render 'form' %>

<%= link_to 'Regresar', lots_path %>

app/views/lots/_tabla_lot.html.erb
<table class="table table-bordered">
    <tr>
      <th>Name</th>
      <th>Descripcion</th>
      <th>Area</th>
      <th>Unidadmedida</th>
      <th>Region</th>
      <th style="width: 60px;"> Acciones</th>
    </tr>
 
   <tbody>
    <% @lots.each do |lot| %>
      <tr>
        <td><%= lot.name %></td>
        <td><%= lot.descripcion %></td>
        <td><%= lot.area %></td>
        <td><%= lot.unidadmedida %></td>
        <td><%= lot.region.name %></td>
        <td  valign="top">
            <%= link_to edit_lot_path(lot), :remote => true, :style=>'height: 14px;', :title=>'Edit', :'data-target'=>"#addModal",  role: "button", :'data-toggle' => "modal" do%> 
              <i class="icon-edit"></i> 
            <% end %> 
            <a style="height: 14px; padding-left: 5px;" title="Delete"
                    data-backdrop="static" data-keyboard="true"
                    href="javascript:;"
                    onclick="show_confirm_modal('<%= lot_path(lot) %>',
                    'Está seguro que desea Eliminar el Lote : <%= lot.name%>');"> 
              <i class="icon-remove"></i> 
            </a>
            <% end %>
        </td>
      </tr>
  </tbody>
</table>

app/views/lots/destroy.js.erb
$('#body_content').html('<%= escape_javascript(render("index")) %>');
$('#messages').html('<%= escape_javascript(render("/layouts/messages")) %>');

app/views/lots/edit.html.erb
<%= render 'edit' %>

app/views/lots/edit.js.erb
<% provide(:boton, 'Salvar Cambios') %>
$('#myModalLabel').html('Editar Lote');
$('#bodyNewRegion').html('<%= escape_javascript(render("form")) %>');

app/views/lots/index.html.erb
<%= render 'index' %>

app/views/lots/index.js.erb
  $("#addModal").modal("hide");
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();
  
 <% if @ajax_search == true %>
  $('#table_div').html('<%= escape_javascript(render("tabla_lot")) %>');
<% else %>
  $('#body_content').html('<%= escape_javascript(render("index")) %>');  
<% end %>  

app/views/lots/new.html.erb
<%= render 'new' %>

app/views/lots/new.js.erb
<% provide(:boton, 'Salvar Cambios') %>
$('#bodyNewRegion').html('<%= escape_javascript(render("form")) %>');

app/views/lots/show.html.erb
<h1>Vista de Lote</h1>


<p id="notice"><%= notice %></p>


<div class="row-fluid">

      <div class="span6">
        <strong>Name:</strong>
        <%= @lot.name %>
      </div>
      
      <div class="span6">
          <strong>Area:</strong>
          <%= @lot.area %>
      </div>
</div>

<div class="row-fluid">
    <div class="span6">
      <strong>Region:</strong>
      <%= @lot.region_id %>
    </div>

    <div class="span6">
      <strong>Unidadmedida:</strong>
      <%= @lot.unidadmedida %>
    </div>

</div>

<div class="row-fluid">
    <div class="span12">
        <strong>Descripcion:</strong>
        <%= @lot.descripcion %>
    </div>
</div>



<%= link_to 'Regresar', lots_path %>

app/views/lots/update.js.erb
$.getScript("/lots/");
history.pushState(null, "", "/lots/");